# Build settings
[build]
  command = ""
  publish = "."

# Redirects and rewrites
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for caching
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"
